cat << EOF > ~/adk-search-agent/handson/agent_engine/.env
GCP_PROJECT_ID=${GCP_PROJECT_ID}
USECASE_ENGINE_DATASTORE_ID=${USECASE_ENGINE_DATASTORE_ID}
GCP_ENGINE_DATASTORE_ID=${GCP_ENGINE_DATASTORE_ID}
SUMMARY_BUCKET_NAME=${SUMMARY_BUCKET_NAME}
SERVICE_ACCOUNT=${SERVICE_ACCOUNT}
GOOGLE_CLOUD_LOCATION=${GOOGLE_CLOUD_LOCATION}
EOF